### PR TITLE
added telemetry page

### LINKED ISSUE #1184: Doc around OSS tracking
Add a doc to tina.io explaining open source tracking.

### PR DESCRIPTION
**Pull request by logan-anderson**
Can be merged once https://github.com/tinacms/tinacms/pull/2450 is merged

Fixes #1184

### CODE REVIEW

**Comment by logan-anderson** [comment]
@jamespohalloran is there anyway to fix the HTML proofer from failing. The reason tina.io/telemetry/ does not exist is because this PR adds it.

**Comment by jamespohalloran** [comment]
> @jamespohalloran is there anyway to fix the HTML proofer from failing. The reason tina.io/telemetry/ does not exist is because this PR adds it.

Hmm, any relative path should be looking in this PR's build directory and not on tina.io/... . I'm not seeing why this is treating this as an absolute link though

**Comment by jamespohalloran** [comment]
> > @jamespohalloran is there anyway to fix the HTML proofer from failing. The reason tina.io/telemetry/ does not exist is because this PR adds it.
> 
> Hmm, any relative path should be looking in this PR's build directory and not on tina.io/... . I'm not seeing why this is treating this as an absolute link though

Ah, it's from an open_graph link. I just removed that check from htmlproofer

**Review by jamespohalloran — APPROVED** [review]
Approved for when the the OSS side is merged!

**Pull request merged**
