### PR TITLE
Add some more info about revamped starter structure

### PR DESCRIPTION
**Pull request by jeffsee55**
This PR adds a little more info to the structure section, but it also removes some that's duplicated in the API references.

### CODE REVIEW

**Review by ashleyjanedoiron — APPROVED** [review]
Looks good! 🚀

**Comment by perkinsjr** [comment]
Looks good to me, merge when ready!

**Comment by logan-anderson** [comment]
I was going through the guide and one thing I think we need to add is what to put in the `Site URL` option when making an app. (a am assuming its http://localhost:3000/)

**Comment by logan-anderson** [comment]
On page 3 it says

> Run Tina Cloud Starter Locally
> Install the project's dependencies:
> `yarn install`

Maybe we should add something before this telling the user they need to clone the repo and change there working directory to it.

**Comment by logan-anderson** [comment]
On the 4th page it says
> Open http://localhost:3000 and click "enter edit mode".
I don't think the edit mode button is there anymore

**Comment by logan-anderson** [comment]
On page 3
> Edit content locally
> Click on the pencil in the lower left-hand corner to open Tina's sidebar which displays a variety of forms with fields you can edit and see updates live on the page. Since we're working locally, clicking save results in changes to your local filesystem.

When opened the APP there was not pencil Icon because I was not in edit mode. We should tell the user how to enter edit mode.

**Comment by ashleyjanedoiron** [comment]
@logan-anderson all of your suggestions have been included in this PR https://github.com/tinacms/tinacms.org/pull/948 !

**Comment by perkinsjr** [comment]
@jeffsee55 can you resolve the conflicts and merge this?

**Pull request merged**
