### PR TITLE
lazy load feature videos

### PR DESCRIPTION
**Pull request by spbyrne**
Trying to use the IntersectionObserver to lazy load videos [based on this guide.](https://web.dev/lazy-loading-video/)

I'm not 100% if it's working but it also doesn't appear to be broken, I would love another set of eyes on the code.

### CODE REVIEW

**Comment by spbyrne** [comment]
On testing the preview deployment on my phone it appears like they all load in together still (any features w/ videos). Maybe the site loads and binds the intersection observer before the dom rendering catches up so it appears like all the videos are above the fold? Just a theory.

**Comment by DirtyF** [comment]
Lighthouse says 14s to interact with the page but it doesn't seem to be related to the video
CleanShot 2021-08-18 at 19 03 33@2x

**Comment by DirtyF** [comment]
On my Ipad the video is not above the fold but feels loaded when I scroll

**Comment by logan-anderson** [comment]
It looks like it is not lazy loading but I definitely could be wrong: https://www.loom.com/share/692ccb0e32d84caf91cfc5d3366a3da2

**Pull request closed without merging**
