### PR TITLE
chore: feedback form reaction required

### PR DESCRIPTION
**Pull request by kendallstrautman**
Clicking a reaction now triggers the feedback form, making the single required form input selected by the time the submit button is visible.

feedback form update

### CODE REVIEW

**Comment by DirtyF** [comment]
Hard to guess it's required https://www.loom.com/share/b804684609eb4880b65b3a3f075d9e2c

**Comment by kendallstrautman** [comment]
Nolan mentioned only showing the Reaction emojis until one is selected and then revealing the rest of the form / submit button — taking cue from Next.js feedback form

**Comment by spbyrne** [comment]
I like that idea; I'll try it out.

**Review by DirtyF — APPROVED** [review]
👍 👍

**Pull request merged**
