### PR TITLE
Add comma to be valid object

### PR DESCRIPTION
**Pull request by matthaias**
Hello, I just tried the TinaCMS Gatsby Guide and thought that a comma was missing here. I just wanted to open a pull request, if I am right I will be happy about a merge. If not, then I could at least have the nice experience to edit the page inline. Greetings Matthias

### CODE REVIEW

**Comment by DirtyF** [comment]
Hacktoberfest spam.

**Comment by matthaias** [comment]
Thank you very much for your answer! I am very sorry, I did not want to spam in any case.  In fact I just wanted to help. I really just did the guide and copied this code and got an error. My thoughts were that with this PR the code can actually be copied and used locally if you try this guide. 
I don't even take part in Hacktoberfest.

After I just checked it again I also saw that `initialValues: data` should also be replaced with `initialValues: data.markdownRemark`, otherwise I would get an error in the page (https://github.com/tinacms/tinacms.org/pull/733/files#diff-d4b719f0c04d07dfb4168c2468026ac4788f3b1cd6a02358695ffd6981e9aaefR25). Of course I can do that too, if I want to.

Anyway, it was a nice experience to open this PR directly through the website, you did a great job! But of course feel free to close this PR if you don't want this change.

Best regards
Matthias

**Comment by DirtyF** [comment]
Sorrry @matthaias for my misjudging 😊 , and thank you for your feedback 🙏

**Review by DirtyF — APPROVED** [review]

**Comment by matthaias** [comment]
No worries, thanks for the approve :) Should I add the change suggested in https://github.com/tinacms/tinacms.org/pull/733#issuecomment-710776351 regarding the `initialValues`?

**Comment by dwalkr** [comment]
@matthaias that would be great!

**Comment by matthaias** [comment]
@dwalkr I just updated it and also adjusted `id: data.markdownRemark.slug` with `id: data.markdownRemark.id` to match this (https://github.com/tinacms/tinacms.org/pull/733/files#diff-d4b719f0c04d07dfb4168c2468026ac4788f3b1cd6a02358695ffd6981e9aaefR63)

Please let me know what you think about it.

**Comment by dwalkr** [comment]
Looks good! Thanks!

**Review by dwalkr — APPROVED** [review]

**Pull request merged**
