### PR TITLE
Editing Updates

### PR DESCRIPTION
**Pull request by spbyrne**
This adds a 'page builder' using a combination of the homepage blocks, pricing page blocks and a generic 'content' block. I've converted a number of pages (privacy, telemetry, security, terms of service) so they can be edited with the new page builder.

Screen Shot 2022-02-22 at 2 37 57 PM
Screen Shot 2022-02-22 at 2 38 21 PM

Uses new rich-text type, admin, visual block selector, new esbuild features.

The new pricing page itself is not included in this PR; I'll create another draft PR to continue collaborating on content.

### CODE REVIEW

**Comment by spbyrne** [comment]
This is failing on Vercel, I'm not familiar with this problem.

`Error: The Serverless Function "blog" is 50.01mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size`

**Comment by logan-anderson** [comment]
@spbyrne this is usually when too many (large) images are used in a blog post. have you added images or larger files?

**Comment by perkinsjr** [comment]
We have cloudinary and we should use it to remove the burden on local images if possible. If you don't have the creds let me know I can share them

**Comment by spbyrne** [comment]
I only added the blog preview images, which are pretty small. We must have been near the limit already. I like cloudinary but I just wanted the blocks previews colocated with content for easier updating; I'm down to remove other large images and migrate them, though. I could move a couple and that would give us what we need for now.

**Comment by logan-anderson** [comment]
@spbyrne You should be able to use the latest version of tinaCMS and @tinacms/cli and not have to use the snapshot version

**Comment by Enigmatical** [comment]
> @spbyrne You should be able to use the latest version of tinaCMS and @tinacms/cli and not have to use the snapshot version

@spbyrne Hope you don't mind, but I took care of that for you 👍

**Comment by logan-anderson** [comment]
I just updated a generated file

**Review by logan-anderson — APPROVED** [review]

**Comment by logan-anderson** [comment]
Looks like @perkinsjr needs to review this before it is merged.

**Review by perkinsjr — APPROVED** [review]

**Pull request merged**
