### PR TITLE
Introduce admin into docs onboarding

### PR DESCRIPTION
**Pull request by jamespohalloran**
DO NOT MERGE UNTIL https://github.com/tinacms/tinacms/pull/2549 IS MERGED/PUBLISHED

### General Contributing:

The introduction of the "CMS" (admin) touches a lot of different docs in subtle ways. One major way, is that using `tina init` now becomes much more viable, as the overhead of setting up contextual editing, is no longer a core requirement.
Information that used to be contained in our "Contextual Editing" concept (Adding the Tina wrapper), is now pulled up into the early setup docs, as it has become a distinct step from setting up contextual editing. 

TODO: 

- [x] Rework "using the editor" section: https://tina.io/docs/using-tina-editor/
This is one area I could use help on is reworking our "Using the editor" doc. It's currently very focused on the contextual editing piece, but it's becoming more complex now that editing can support editing with/without contextual-editing integration. This doc should be friendly to devs/non-devs
(PR https://github.com/tinacms/tinacms.org/pull/1232)
- [x] The [getting started](https://tinacms-site-next-git-admin-onboarding-tinacms.vercel.app/docs/setup-overview/) doc should become more of an index page for: (`tina init` on existing site, using a starter, `UI quickstart`)
- [x] Remove Tina wrapper setup from contextual-editing
- [x] Hopefully move forward with this task: https://github.com/tinacms/tinacms/issues/2545 which will make the setup-docs much simpler on initial sites.
If we do move forward with it, we should have a reference doc for `TinaEditProvider`, and the `TinaCMS` components.
- [x] Rework/Replace existing add-tina-to-next guide
I'm hoping that most of the content from this guide can be covered in the main onboarding docs (Introduction/Core-concepts), instead of this section needing its own guide. The guide has started to feel pretty dated. 

~~- [ ] Bonus: Our [data-fetching doc](https://tinacms-site-next-git-admin-onboarding-tinacms.vercel.app/docs/features/data-fetching/) shouldn't use `useTina`, as contextual editing is an optional concept: https://github.com/tinacms/tinacms.org/issues/1227~~

### All New Content Submissions: (To be confirmed by reviewer)

* [ ] Title is short & specific
* [ ] Headers are logically ordered & consistent
* [ ] Purpose of document is explained in the first paragraph
* [ ] Procedures are tested and work
* [ ] Any technical concepts are explained or linked to
* [ ] Document follows structure from templates
* [ ] All links work
* [ ] Spelling and grammer checker has been run
* [ ] Graphics and images are clear and useful
* [ ] Any prerequisites and next steps are defined.

### CODE REVIEW

**Comment by spbyrne** [comment]
Screen Shot 2022-02-23 at 2 46 44 PM

I pushed up a hard-coded mockup page for the overview design. Open to feedback/ideas; the content is just mock.

**Comment by Enigmatical** [comment]
So far, I really like the streamlined approach (three ways to get going is a nice, concise way to handle our different types of users).

I noticed this file was gutted:
https://github.com/tinacms/tinacms.org/pull/1226/files#diff-7349b5c7f0dd200645c64944973bc6ab5784a61c7ba52e4e212725a44579390d

Is this missing the changes I made?
https://github.com/tinacms/tinacms.org/pull/1232

**Comment by jamespohalloran** [comment]
> So far, I really like the streamlined approach (three ways to get going is a nice, concise way to handle our different types of users).
> 
> I noticed this file was gutted: https://github.com/tinacms/tinacms.org/pull/1226/files#diff-7349b5c7f0dd200645c64944973bc6ab5784a61c7ba52e4e212725a44579390d
> 
> Is this missing the changes I made? #1232

Your new RouteMapper and "Accessing contextual-editing from the CMS" sections should still be there! https://tinacms-site-next-git-admin-onboarding-tinacms.vercel.app/docs/tinacms-context/
I did however remove some of the original info on handling using the TinaEditProvider, and handling dynamic imports (Now that it's (soon to be ) done implicitly with: https://github.com/tinacms/tinacms/pull/2549)

**Review by Enigmatical — APPROVED** [review]
Looks good to me :)

**Pull request merged**
