### PR TITLE
Add documentation for plugin authoring

### PR DESCRIPTION
**Pull request by chrisdmacrae**
In this pull request I:

- [ ] Submitted a doc detailing third-party plugin authoring using tsdx
  - [ ] Walks through setting up a basic:
     - Toolbar extension
     - API
     - Field
     - Modal
     - Global form
  - [ ] Walks through common pitfalls of multiple versions of reacts
  - Discusses two approaches
     - [ ] Working with other sites locally OR;
     - [ ] Using the jest test environment for local development & testing
- [ ] Updates the cms/plugins doc to have a CTA to learn about authoring

### CODE REVIEW

**Comment by kendallstrautman** [comment]
Is this still in process @chrisdmacrae? Or should we close for now?

**Comment by chrisdmacrae** [comment]
@kendallstrautman still in progress. I'm doing about an hour of work a week at the moment, in between other work!

But this should be good, as @logan-anderson and I have developed three "third-party" plugins now, and have it down to a science.

**Comment by logan-anderson** [comment]
Here are some notes/docs I made when making a new 3rd party tina package


# How to make an external project with tina

## bootstrap the project

`npx tsdx create react-tinacms-localization`

if you want to have full control over eslint and prettier you can [follow this guide to set them up](https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project)


## setup with [yalc](https://www.npmjs.com/package/yalc)

-  install yalc globally
`yarn global add yalc`
or
`npm i -g yalc`

in your package code run 
`yalc publish`
this will publish all the code that would be in an npm package to your local "yalc store"

next in the repo where you wish to test your package run 
`yalc add <name of package>`


now in your code, you can have 

```
import { somModule } from '<name of package>'
```


if you make a change to your package you can run
`yarn build && yalc push`
this will update the store with the new code and anything using the package from the yalc store will automatically get the updates :smile: 

depending on what framework you are using and how it handles how module reloading you may how to restart your dev server (this is the case for nextjs)

@tinacms/maintainers @chrisdmacrae let me know what you guys think

**Comment by chrisdmacrae** [comment]
Kudos go to @jeffsee55 for pointing us in the direction of yalc

**Comment by kendallstrautman** [comment]
This PR has grown quite stale. If it's alright, I'd like to close it and we can reopen when further action is taken.

**Pull request closed without merging**
