### PR TITLE
kneaded to update tina description

### PR DESCRIPTION
**Pull request by mittonface**
Please pull these awesome changes in!

### CODE REVIEW

**Comment by spbyrne** [comment]
Carefully considering these changes before I merge this, probably need some input from @ncphillips

**Comment by ncphillips** [comment]
I like it, but I think @scottgallant might be _sourdough_

**Comment by scottgallant** [comment]
Leave it up to @mittonface to make a bun pun

**Comment by ncphillips** [comment]
At _yeast_ he has the dignity to do it from a fork

**Comment by mittonface** [comment]
I get this feeling everybody would be more comfortable with _leaven_ these changes out.

**Pull request closed without merging**
