### PR TITLE
added media to tina-starter guide

### PR DESCRIPTION
**Pull request by logan-anderson**
Once https://github.com/tinacms/tinacms.org/pull/946 is merged I will link to those media docs instead of the package readme

### CODE REVIEW

**Review by ashleyjanedoiron — APPROVED** [review]
Just pushed a few minor wording/formatting tweaks, but other than that looks good to me!

**Comment by logan-anderson** [comment]
Thanks @perkinsjr and @DirtyF I was able to use a video instead of a gif that that seemed to fix the deployment issue. @ashleyjanedoiron This is ready for review again 🎉 .

**Review by ashleyjanedoiron — DISMISSED** [review]
Looks good 🚀 !

**Comment by logan-anderson** [comment]
The video is working for me on brave and safari. https://tinacms-site-next-git-add-media-guide-tinacms.vercel.app/guides/tina-cloud/starter/connect-to-tina-cloud/

**Review by DirtyF — APPROVED** [review]
Fine by me. Video works fine in Firefox too.

**Pull request merged**
