### PR TITLE
Release notes

### PR DESCRIPTION
**Pull request by ncphillips**

### CODE REVIEW

**Comment by ncphillips** [comment]
@dwalkr or @kendallstrautman 

The `src` of the `<iframe>` in the Markdown body gets mangled. I can switch to an image/link if necessary

image

**Comment by kendallstrautman** [comment]
Yikes, Is that Tina's doing? Can we just manually write the src?

**Comment by ncphillips** [comment]
It's not Tina doing it it's `react-markdown`

**Comment by ncphillips** [comment]
Wait no you were right, it _was_ the wysiwyg

**Pull request merged**
